:PROPERTIES:
:ID:       1c09d4f3-1f72-49f6-930d-e2d92473a979
:END:

TITLE: Update July 28, 2025
#+DATE: <2025-07-28 Sun 17:30>
#+filetags: :update:

* What have I been up to?
Whoops! I missed this month's update by a /long/ shot, but I still want to get it out there before the end of the month.

This month was busy busy. I released [[https://github.com/miracle-wm-org/miracle-wm/releases/tag/v0.6.0][v0.6.0 of miracle-wm]] which adds a bunch of new features, go and check it out if you haven't already! I am nearly finished with the sway/i3 IPC support and have big plans to wrap that up before the middle of August. There really isn't much more to go on that front so I might as well close that chapter. On top of that, the more interesting features of miracle that I have planned (e.g. some built-in shell integrations) are motivating me to wrap up the boring parts first.

Aside from miracle, I've continued to land a bunch of things in Mir recently around accessibility. The magnifier work is finally done, so go check that out if you use that feature in your day-to-day! I also did a /ton of work/ to fix screenshooting on rotated displays. We were ignoring [[https://wayland.app/protocols/wayland#wl_surface:request:set_buffer_transform][wl_surface::set_buffer_transform]] in a big way. Now that we're not doing that, your screenshots should like perfect every time!

Last but not least, the team has been making waves implementing multi-window in the Flutter toolkit. That's some really interesting and exciting work, so stay tuned for that if you're a Flutter developer!

That's all I got! I will make another post shortly, maybe once miracle v0.7.0 is out. Have a great rest of your summer/winter 🪐


