#include "sun_frag.h"

const char* shader_sun_frag = "varying lowp vec4 VertexColor; \n"
"varying lowp vec2 TexCoord; \n"
"uniform lowp float time; \n"
" \n"
"// Simple noise function for edge distortion \n"
"lowp float noise(lowp vec2 p) { \n"
"    return sin(p.x * 10.0 + time) * cos(p.y * 10.0 + time * 0.5) * 0.5 + 0.5; \n"
"} \n"
" \n"
"void main() { \n"
"    // TexCoord is now normalized: center is (0,0), edges are at distance ~1 \n"
"    lowp float dist = length(TexCoord); \n"
" \n"
"    // Add animated noise to the edge \n"
"    lowp float angle = atan(TexCoord.y, TexCoord.x); \n"
"    lowp float wave = sin(angle * 8.0 + time * 2.0) * 0.05 + sin(angle * 4.0 - time * 1.5) * 0.03; \n"
"    lowp float noiseValue = noise(TexCoord + time * 0.1) * 0.02; \n"
" \n"
"    // Create soft edge using smoothstep - ensure fade reaches zero at the actual edge \n"
"    lowp float innerEdge = 0.8; \n"
"    lowp float outerEdge = 1.0; \n"
"    lowp float alpha = 1.0 - smoothstep(innerEdge, outerEdge, dist); \n"
" \n"
"    // Apply wave distortion to the edge \n"
"    alpha *= 1.0 - smoothstep(0.85 + wave + noiseValue * 2.0, 1.0, dist); \n"
" \n"
"    // Make edges more transparent but not too much \n"
"    alpha = alpha * alpha; \n"
" \n"
"    // Add slight glow effect at the edge \n"
"    lowp float glow = smoothstep(0.5, 0.8, dist) * (1.0 - smoothstep(0.8, 1.0, dist)); \n"
" \n"
"    // Create orange gradient from center \n"
"    lowp vec3 orangeColor = vec3(1.0, 0.5, 0.1); \n"
"    lowp float centerGradient = smoothstep(0.6, 0.0, dist); \n"
"    lowp vec3 baseColor = mix(VertexColor.rgb, orangeColor, centerGradient * 0.6); \n"
" \n"
"    // Mix in the glow with a brighter color \n"
"    lowp vec3 glowColor = baseColor * 1.3; \n"
"    lowp vec3 finalColor = mix(baseColor, glowColor, glow * 0.5); \n"
" \n"
"    gl_FragColor = vec4(finalColor, VertexColor.a * alpha); \n"
"} \n"
" \n";
